# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Deploy on Release

on:
  release:
    types: [ published ]
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    name: Setup, Build and Publish    
    runs-on: ubuntu-latest
    
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Get Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: 'Login to docker with GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build with Maven"
        working-directory: ./Main/SpringExample/demo-spring-app-master/
        run: |
          mvn --batch-mode clean compile jib:dockerBuild -Pproduction
          docker tag shippingappb:latest ghcr.io/${{ github.repository_owner }}/shipping-app-b:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/shipping-app-b:${{ env.RELEASE_VERSION }}
      - name: Send Deploy Notification to Integration Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: com619-2021/IntegrationB
          event-type: deploy
          client-payload: '{"image_owner": "SHIPPING_IMAGE", "image_tag": "ghcr.io/${{ github.repository_owner }}/shipping-app-b:${{ env.RELEASE_VERSION }}"}'
